version : '3'
services:
  monolith:
    build: .
    entrypoint: []
    ports: 
      - "8090:8080"
    environment : 
      - SHOP_MONOLITH_BIND_ADDRESS = :8080
  orders:
    build: .
    entrypoint : []
    ports:
      - "8070:8080"
    environment : 
      - SHOP_ORDERS_SERVICE_BIND_ADDRESS = :8080
      - SHOP_RABBITMQ_ADDRESS = rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE = orders-to-pay
      - SHOP_ORDERS_SERVICE_ADDRESS = http://orders:8080
    depends_on :
      - rabbitmq
  payments:
    build : .
    entrypoint: []
    environment:
      - SHOP_RABBITMQ_ADDRESS = rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE = orders-to-pay
    depends_on:
      rabbitmq
  shop:
    build : .
    entrypoint: []
    environment:
      - SHOP_SERVICE_BIND_ADDRESS = :8080
    ports:
      - "8071:8080"
    depends_on :
      - rabbitmq  

